# Development Docker Compose file
# Use this for local development with hot reloading

version: '3.8'

services:
  explainshot-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"  # Vite dev server default port
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    command: npm run dev
    restart: unless-stopped
