version: '3.8'

services:
  explainshot-site:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.explainshot.rule=Host(`explainshot.local`)"
      - "traefik.http.services.explainshot.loadbalancer.server.port=8080"

  # Optional: Add a reverse proxy like Traefik
  # traefik:
  #   image: traefik:v2.10
  #   command:
  #     - --api.insecure=true
  #     - --providers.docker=true
  #     - --providers.docker.exposedbydefault=false
  #     - --entrypoints.web.address=:80
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   restart: unless-stopped
